title: Мій сайт
description: Документація сайту

remote_theme: just-the-docs/just-the-docs

url: https://vitapl.github.io
baseurl: /firstmark

search_enabled: true
color_scheme: light

aux_links:
  GitHub:
    - https://github.com/vitapl
